//
// Generated file, do not edit! Created by opp_msgc 4.3 from messages/CSynchMsg.msg.
//

#ifndef _CSYNCHMSG_M_H_
#define _CSYNCHMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/CSynchMsg.msg</tt> by opp_msgc.
 * <pre>
 * message CSynchMsg {
 *     double timestamp;
 *     int skewValue;
 *     int typeOperation;
 * }
 * </pre>
 */
class CSynchMsg : public ::cMessage
{
  protected:
    double timestamp_var;
    int skewValue_var;
    int typeOperation_var;

  private:
    void copy(const CSynchMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CSynchMsg&);

  public:
    CSynchMsg(const char *name=NULL, int kind=0);
    CSynchMsg(const CSynchMsg& other);
    virtual ~CSynchMsg();
    CSynchMsg& operator=(const CSynchMsg& other);
    virtual CSynchMsg *dup() const {return new CSynchMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);
    virtual int getSkewValue() const;
    virtual void setSkewValue(int skewValue);
    virtual int getTypeOperation() const;
    virtual void setTypeOperation(int typeOperation);
};

inline void doPacking(cCommBuffer *b, CSynchMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CSynchMsg& obj) {obj.parsimUnpack(b);}


#endif // _CSYNCHMSG_M_H_
